### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ghost** [uberblah/reddit_scrape#1]
Could you please provide instruction on how to download comments from a subreddit?

**Comment by uberblah** [comment]
I'm afraid I haven't touched this in a very long time. I'm not even sure if the reddit client libraries I was using will still work the same way.

I'm pretty sure I was using a non-subreddit-specific API from reddit that feeds a certain portion of _all_ incoming reddit comments to the scraper. You can, however, see what subreddits the messages were in, once you've pulled them. If there's a way to make it pull only for a specific subreddit, I don't know how that works.

For more information, maybe look at the praw library documentation?
https://praw.readthedocs.io/en/latest/
